name: mypipeline

on:
  push:
    branches: main

  pull_request: 
    branches: main
    
jobs:
  Creating_Docker_Image:
    runs-on: ubuntu-latest

    steps:
    - name: Code_Checkout
      uses: actions/checkout@v4
      
    - name: Building Docker Image
      run: docker build -t myimage:latest -f Dockerfile .
